# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths C:/Xilinx_proj/ip_repo/ovtop/ovtop.srcs/sources_1/imports/ovtop [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Xilinx_proj/ip_repo/ovtop/ovtop.srcs/sources_1/imports/ovtop/I2C_OV7670_RGB444_Config.v
  C:/Xilinx_proj/ip_repo/ovtop/ovtop.srcs/sources_1/imports/ovtop/I2C_Controller.v
  C:/Xilinx_proj/ip_repo/ovtop/ovtop.srcs/sources_1/imports/ovtop/ov7670_capture.v
  C:/Xilinx_proj/ip_repo/ovtop/ovtop.srcs/sources_1/imports/ovtop/I2C_AV_Config.v
  C:/Xilinx_proj/ip_repo/ovtop/ovtop.srcs/sources_1/imports/ovtop/debounce.v
  C:/Xilinx_proj/ip_repo/ovtop/ovtop.srcs/sources_1/imports/ovtop/ov7670_top.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx_proj/ip_repo/ovtop/ovtop.cache/wt [current_project]
set_property parent.project_dir C:/Xilinx_proj/ip_repo/ovtop [current_project]
synth_design -top ov7670_top -part xc7a100tcsg324-1
write_checkpoint ov7670_top.dcp
report_utilization -file ov7670_top_utilization_synth.rpt -pb ov7670_top_utilization_synth.pb
